title: TEST
description: test
url: alissli.github.io
permalink: /:title /github-pages

author: alissli
author-img: 
about-author: 育儿育己
facebook: 
github: alissli
email: 45923432@qq.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

theme: jekyll-theme-cayman
